### ISSUE TITLE
fix calendar styling

### ISSUE THREAD

**Issue by lrothschildshea** [ripples/Present#14]
- make calendar larger so it is easier to read
- change styling of popup menus to match the rest of the application

**Comment by jbaileydev** [comment]
Just fixed calendar size. Will change styling of popup messages later tonight/tomorrow.

**Comment by jbaileydev** [comment]
Finished modal re-work and matches styling of application. Easily re-styled if the application style changes as well. Will extend this to messages in next day or two.
