### ISSUE TITLE
Combine redundant configuration files, setup files, etc.

### ISSUE THREAD

**Issue by jbaileydev** [ripples/Present#24]

**Comment by lrothschildshea** [comment]
Can we get more information on this? We have like one optional config file to begin with so i'm not sure what we are combining.

**Comment by jbaileydev** [comment]
I think this was meant more for the capture server side of things.

**Comment by pauled** [comment]
It's on the capture server side. It seems like everytime a machine is set
up there turn out to be lots of different things that need configuration
with different files. It may be that we just need to reorganize on the
capture side to clean everything up as we now use a different methodology
than when we first started.

**Comment by lrothschildshea** [comment]
closing because it is not an issue for this repo. An issue should be opened up in the capture repo
